TrainConfig:
  batch_size: 4096
  epochs: 100
  callbacks:
    EarlyStopping:
      monitor: val_loss
      mode: min
      patience: 10
      restore_best_weights: true
    ReduceLROnPlateau:
      monitor: val_loss
      mode: min
      factor: 0.5
      patience: 5
    TerminateOnNaN: {}
  validation_split: 0.1
  verbose: 0